/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import controlador.ControladorMozo;
import dominio.IMesa;
import dominio.Mozo;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author william
 */
public class PanelMesas extends javax.swing.JPanel implements ActionListener {
    //implementa ActionListener para poder determinar que botonMesa se apreto
    
    private ControladorMozo controlador;
    private Mozo mozo;
    
    /**
     * Creates new form PanelMesas
     */
    public PanelMesas() {
        initComponents();
    }
    public PanelMesas(Mozo m, ControladorMozo c) {
        initComponents();
        controlador = c;
        mozo = m;
        this.mostrar(m.getMesas());
    }
    public void mostrar(ArrayList<IMesa> mesas){
        removeAll();
        GridLayout layout = new GridLayout(1,mesas.size());
        setLayout(layout);
        for(IMesa mesa : mesas){
            BotonMesa bm = new BotonMesa(mesa);
            
            //agrego el boton como escucha
            bm.addActionListener(this);
            
            //agrego el boton al panel
            add(bm);
        }
        validate();//refresh
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout());
    }// </editor-fold>//GEN-END:initComponents
    
    
    @Override
    public void actionPerformed(ActionEvent e) {
        BotonMesa origen = (BotonMesa)e.getSource();
        IMesa m = origen.getMesa();
        controlador.mostrarMesa(m);
        controlador.guardarSeleccionada(m);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
