/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import controlador.ControladorPedido;
import dominio.IMesa;
import dominio.Producto;
import dominio.RestaurantException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import vista.VistaPedido;

/**
 *
 * @author william
 */
public class VentanaAgregarPedido extends javax.swing.JFrame implements VistaPedido{
    
    private ControladorPedido controlador;
    //private IMesa mesaSeleccionada;
    /**
     * Creates new form VentanaAgregarProducto
     */
    public VentanaAgregarPedido() {
        initComponents();
    }

    VentanaAgregarPedido(IMesa mesaSeleccionada) {
        initComponents();
        this.controlador = new ControladorPedido(this, mesaSeleccionada);

        controlador.cargarProductos();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstProductos = new javax.swing.JList();
        txtCantidad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jScrollPane1.setViewportView(lstProductos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 20, 350, 170);

        txtCantidad.setText("1");
        getContentPane().add(txtCantidad);
        txtCantidad.setBounds(20, 200, 190, 30);

        jButton1.setText("Agregar Pedido");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 240, 150, 23);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.agregarPedido();
    }//GEN-LAST:event_jButton1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstProductos;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cargarProductos(ArrayList<Producto> listarProductos) {
        lstProductos.setListData(listarProductos.toArray());
    }

    private void agregarPedido() {
        int cantidad = Integer.parseInt(txtCantidad.getText());
        Producto prod = (Producto) lstProductos.getSelectedValue();
        try{ 
            controlador.agregarPedido(prod,cantidad);
            this.dispose();
        }catch(RestaurantException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());          
        }
        
            
    }


}
