/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import controlador.ControladorMozo;
import dominio.Transferencia;
import javax.swing.JOptionPane;

/**
 *
 * @author william
 */
public class VentanaMensajeAceptarTransferencia extends javax.swing.JFrame {
    
    private ControladorMozo controlador;
    private Transferencia transferencia;
    /**
     * Creates new form VentanaMensajeAceptarTransferencia
     */
    public VentanaMensajeAceptarTransferencia() {
        initComponents();
    }
    
    public VentanaMensajeAceptarTransferencia(ControladorMozo controlador, Transferencia trans) {
        this.controlador = controlador;
        this.transferencia = trans;
        initComponents();
        txtInfo.setText("Transferencia de mesa "
                + trans.getMesa().toString());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTimer = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtInfo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblTimer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTimer.setText("0");
        getContentPane().add(lblTimer);
        lblTimer.setBounds(20, 30, 350, 50);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar);
        btnAceptar.setBounds(20, 190, 120, 23);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(250, 190, 120, 23);
        getContentPane().add(txtInfo);
        txtInfo.setBounds(30, 90, 320, 80);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
         controlador.aceptarTransferencia(transferencia);
         dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        controlador.rechazarTransferencia(transferencia);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JTextField txtInfo;
    // End of variables declaration//GEN-END:variables

    public void actualizarTimer(int tiempo) {
        lblTimer.setText(tiempo + "");
        
    }
}
