/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import controlador.ControladorInicio;
import javax.swing.JOptionPane;
import vista.VistaInicio;

/**
 *
 * @author william
 */
public class VentanaInicio extends javax.swing.JFrame implements VistaInicio{
    
    private ControladorInicio controlador;
    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
        controlador = new ControladorInicio(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMozo = new javax.swing.JButton();
        btnGestor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        btnMozo.setText("Mozo");
        btnMozo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMozoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMozo);
        btnMozo.setBounds(160, 130, 70, 23);

        btnGestor.setText("Gestor");
        btnGestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestorActionPerformed(evt);
            }
        });
        getContentPane().add(btnGestor);
        btnGestor.setBounds(160, 170, 73, 23);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMozoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMozoActionPerformed
        new VentanaLoginMozo().setVisible(true);
    }//GEN-LAST:event_btnMozoActionPerformed

    private void btnGestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestorActionPerformed
        new VentanaLoginGestor().setVisible(true);
    }//GEN-LAST:event_btnGestorActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controlador.salir();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestor;
    private javax.swing.JButton btnMozo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cerrar(boolean b) {
        if(b){
            dispose();
        }else{
            JOptionPane.showMessageDialog(this, "No puede salir! Hay pedidos pendientes!");
        } 
    }
}
