/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import controlador.ControladorLoginGestor;
import dominio.Gestor;
import dominio.Mozo;
import javax.swing.JOptionPane;
import vista.VistaLoginGestor;

/**
 *
 * @author william
 */
public class VentanaLoginGestor extends javax.swing.JFrame implements VistaLoginGestor {

    private ControladorLoginGestor controlador;

    /**
     * Creates new form VentanaLogin
     */
    public VentanaLoginGestor() {
        initComponents();
        controlador = new ControladorLoginGestor(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nombre de Usuario");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 70, 140, 14);

        txtNombre.setText("1");
        getContentPane().add(txtNombre);
        txtNombre.setBounds(120, 90, 170, 20);

        jLabel2.setText("Clave");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 130, 90, 14);

        txtClave.setText("1");
        getContentPane().add(txtClave);
        txtClave.setBounds(120, 150, 170, 20);

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar);
        btnIngresar.setBounds(120, 200, 90, 23);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        String nombre = txtNombre.getText();
        String clave = txtClave.getText();
        this.ingresar(nombre, clave);
        
    }//GEN-LAST:event_btnIngresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private void ingresar(String nombre, String clave) {
        
        if(nombre.isEmpty()){
           JOptionPane.showMessageDialog(this, "Debe ingresar un nombre!");
        }else if(clave.isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe ingresar su clave!");
        }else{
            controlador.LoginGestor(nombre, clave);
        } 
    }
     @Override
    public void ingresarGestor(Gestor g) {
        dispose();
        new VentanaUPP(g).setVisible(true);
    }
    @Override
    public void error(String message) {
        JOptionPane.showMessageDialog(this, message);    
    }

}
