/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import controlador.ControladorAsignacionCliente;
import vista.VistaAsignacionCliente;
import dominio.Cliente;
import dominio.IMesa;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author william
 */
public class VentanaAsignacionCliente extends javax.swing.JFrame implements VistaAsignacionCliente{

    private ControladorAsignacionCliente controlador;
    /**
     * Creates new form VentanaAsignacionCliente
     */
    public VentanaAsignacionCliente() {
        initComponents();
    }
    public VentanaAsignacionCliente(ArrayList<Cliente> verClientesRegistrados, IMesa mesaSeleccionada) {
        controlador = new ControladorAsignacionCliente(mesaSeleccionada,this);
        initComponents();
        controlador.cargarLista(verClientesRegistrados);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstClientesRegistrados = new javax.swing.JList();
        btnAsignarCliente = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jScrollPane1.setViewportView(lstClientesRegistrados);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 370, 190);

        btnAsignarCliente.setText("Asignar");
        btnAsignarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsignarCliente);
        btnAsignarCliente.setBounds(50, 230, 110, 23);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(200, 230, 110, 23);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsignarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarClienteActionPerformed
        Cliente unC = (Cliente)lstClientesRegistrados.getSelectedValue();
        controlador.asignarClienteMesa(unC);
        this.dispose();
    }//GEN-LAST:event_btnAsignarClienteActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarCliente;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstClientesRegistrados;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cargarLista(ArrayList<Cliente> verClientesRegistrados) {
        lstClientesRegistrados.setListData(verClientesRegistrados.toArray());
    }

    @Override
    public void error(String message) {
        JOptionPane.showMessageDialog(this,message);
    }
}
