/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import controlador.ControladorMozo;
import controlador.ControladorTransferencia;
import dominio.IMesa;
import dominio.Mozo;
import dominio.Sistema;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import vista.VistaTransferencia;

/**
 *
 * @author william
 */
public class VentanaTransferencia extends javax.swing.JFrame implements VistaTransferencia{

    /**
     * Creates new form VentanaTransferencia
     */
    private ControladorTransferencia controlador;
    private Mozo origen;
    
    public VentanaTransferencia() {
        initComponents();
    }

    VentanaTransferencia(IMesa mesaSeleccionada) {
        initComponents();
        this.origen = mesaSeleccionada.verMozo();
        this.controlador = new ControladorTransferencia(this,origen,mesaSeleccionada);
        controlador.cargarMozosLogueados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstMozoDestino = new javax.swing.JList();
        btnTransferir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jScrollPane1.setViewportView(lstMozoDestino);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 20, 330, 130);

        btnTransferir.setText("Transferir");
        btnTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirActionPerformed(evt);
            }
        });
        getContentPane().add(btnTransferir);
        btnTransferir.setBounds(140, 200, 110, 23);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed
        this.avisarComienzoTransferencia();
        dispose();
    }//GEN-LAST:event_btnTransferirActionPerformed

    private void avisarComienzoTransferencia() {
        Mozo destino = (Mozo)lstMozoDestino.getSelectedValue();
        if(destino!=null){
            controlador.avisarComienzoTransferencia(destino);
            
        }else{
            JOptionPane.showMessageDialog(this, "Debe seleccionar un destino");
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTransferir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstMozoDestino;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cargarMozosLogueados(ArrayList<Mozo> verMozosLoguados) {
        lstMozoDestino.setListData(verMozosLoguados.toArray());
    }

    @Override
    public void error(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    
}
